{
  "branches": [ "main" ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/github",
      {
        "assets": [
          { "path": "artifacts/cap.linkml.yaml", "label": "Linkml scheme" },
          { "path": "artifacts/cap.shacl.ttl", "label": "SHACL Shape" },
          { "path": "artifacts/cap.owl.ttl", "label": "Ontology (turtle)" },
          { "path": "artifacts/cap.owl.xml", "label": "Ontology (XML)" },
          { "path": "artifacts/cap.jsonld", "label": "JSON-LD Context" }
         ]
      }
    ],
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md"
      }
    ],
    [ "@semantic-release/git", {
      "assets": [ "package.json", "package-lock.json", "CHANGELOG.md" ],
      "message": "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"
    } ]
  ]
}
