{
  "branches": [ "main" ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/github",
      {
        "assets": [
          { "path": "artifacts/shapes.shacl.ttl", "label": "SHACL Shapes" },
          { "path": "artifacts/ontology.ttl", "label": "Ontology (OWL)" },
          { "path": "artifacts/context.jsonld", "label": "JSON-LD Context" }
        ]
      }
    ],
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md"
      }
    ],
    [ "@semantic-release/git", {
      "assets": [ "package.json", "package-lock.json", "CHANGELOG.md" ],
      "message": "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"
    } ]
  ]
}
