name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build-linkml:
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    container:
      image: linkml/linkml:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pip3 install rdflib
      - name: Build shapes (SHACL)
        run: gen-shacl linkml/conformity_assessment.yml --no-mergeimports --closed --suffix Shape > shapes.shacl.ttl
      - name: Build schemas (OWL)
        run: gen-owl --no-use-native-uris --assert-equivalent-classes linkml/conformity_assessment.yml > ontology.ttl
      - name: Generate JSON-LD context
        run: gen-jsonld-context linkml/conformity_assessment.yml --no-mergeimports > context.jsonld
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Schemas
          path: |
            shapes.shacl.ttl
            ontology.ttl
            context.jsonld
          retention-days: 7

  release:
    runs-on: ubuntu-latest
    needs: build-linkml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Schemas
          path: artifacts
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog@6.0.0
            @semantic-release/github
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
